; This file was auto-generated by Eastern Standard

api = 2
core = 7.x

; Acuiqa Drupal

projects[drupal][type] = "core"
projects[drupal][download][type] = "get"
;ver. 7.28
;projects[acquia][download][url] = "https://www.acquia.com/downloads/3175681/full/tar.gz"
;ver. 7.31
projects[drupal][download][url] = "http://www.acquia.com/downloads/3191106/full/zip"


; Modules

;projects[acquia_connector][version] = "7.x-2.14"

;projects[acquia_purge][version] = "7.x-1.0-beta2"

projects[adaptive_image][version] = "7.x-1.4"

projects[admin_menu][version] = "7.x-3.0-rc3"

projects[admin_views][version] = "7.x-1.2"

projects[advanced_help][version] = "7.x-1.0"

projects[auto_nodetitle][version] = "7.x-1.0"

projects[backup_migrate][version] = "7.x-2.4"

projects[bean][version] = "7.x-1.7"

projects[block_class][version] = "7.x-1.1"

projects[blockify][version] = "7.x-1.2"

projects[calendar][version] = "7.x-3.4"

projects[captcha][version] = "7.x-1.0-beta2"

projects[ckeditor][version] = "7.x-1.9"

projects[ckeditor_link][version] = "7.x-2.2"

projects[coffee][version] = "7.x-1.0"

projects[colorbox][version] = "7.x-2.3"

projects[conditional_styles][version] = "7.x-2.1"

projects[context][version] = "7.x-3.2"

projects[ctools][version] = "7.x-1.4"

projects[date][version] = "7.x-2.6"

projects[ddblock][version] = "7.x-1.0"

projects[delta][version] = "7.x-3.0-beta11"

projects[diff][version] = "7.x-3.2"

projects[draggableviews][version] = "7.x-2.0"

projects[ds][version] = "7.x-2.4"

projects[email][version] = "7.x-1.2"

projects[empty_page][version] = "7.x-1.0"

projects[entity][version] = "7.x-1.4"

projects[entityreference][version] = "7.x-1.1"

projects[eva][version] = "7.x-1.2"

projects[expire][version] = "7.x-2.0-rc3"

projects[extlink][version] = "7.x-1.12"

;projects[fast_404][version] = "7.x-1.3"

projects[features][version] = "7.x-2.0"

projects[feeds][version] = "7.x-2.0-alpha8"

projects[feeds_xpathparser][version] = "7.x-1.0-beta4"

projects[fences][version] = "7.x-1.0"

projects[field_collection][version] = "7.x-1.0-beta5"

projects[field_group][version] = "7.x-1.1"

projects[field_permissions][version] = "7.x-1.0-beta2"

projects[filefield_sources][version] = "7.x-1.9"

projects[fontyourface][version] = "7.x-2.5"

projects[front][version] = "7.x-2.1"

projects[globalredirect][version] = "7.x-1.5"

projects[google_analytics][version] = "7.x-1.3"

projects[honeypot][version] = "7.x-1.16"

projects[imce][version] = "7.x-1.6"

projects[imce_wysiwyg][version] = "7.x-1.0"

projects[job_scheduler][version] = "7.x-2.0-alpha3"

projects[jquery_plugin][version] = "7.x-1.0"

projects[jquery_update][version] = "7.x-2.2"

projects[ldap][version] = "7.x-2.0-beta8"

projects[less][version] = "7.x-2.6"

projects[libraries][version] = "7.x-2.0"

projects[link][version] = "7.x-1.0"

projects[linkchecker][version] = "7.x-1.1"

projects[manual-crop][version] = "7.x-1.4"

projects[media][version] = "7.x-1.4"

projects[memcache][version] = "7.x-1.0"

projects[menu_attributes][version] = "7.x-1.0-rc2"

projects[menu_block][version] = "7.x-2.3"

projects[menu_breadcrumb][version] = "7.x-1.3"

projects[menu_position][version] = "7.x-1.1"

projects[menu_views][version] = "7.x-2.0"

projects[metatags_quick][version] = "7.x-2.5"

projects[module_filter][version] = "7.x-1.7"

;projects[mollom][version] = "7.x-2.6"

projects[node_clone][version] = "7.x-1.0-rc1"

projects[node_export][version] = "7.x-3.0"

projects[oauth][version] = "7.x-3.1"

projects[omega_tools][version] = "7.x-3.0-rc4"

projects[override_node_options][version] = "7.x-1.12"

projects[page_title][version] = "7.x-2.7"

projects[panels][version] = "7.x-3.3"

projects[pathauto][version] = "7.x-1.2"

projects[profile2][version] = "7.x-1.2"

projects[profile2_regpath][version] = "7.x-1.10"

projects[quickbar][version] = "7.x-2.0-beta1"

projects[quicktabs][version] = "7.x-3.6"

projects[readonlymode][version] = "7.x-1.1"

projects[recaptcha][version] = "7.x-1.8"

projects[redirect][version] = "7.x-1.0-rc1"

projects[references][version] = "7.x-2.0"

projects[resp_img][version] = "7.x-1.3"

projects[respondjs][version] = "7.x-1.1"

projects[restrict_ip][version] = "7.x-1.0-rc2"

projects[revisioning][version] = "7.x-1.8"

projects[riddler][version] = "7.x-1.2"

projects[rules][version] = "7.x-2.5"

projects[save_draft][version] = "7.x-1.4"

projects[scheduler][version] = "7.x-1.0"

projects[securepages][version] = "7.x-1.0-beta2"

projects[site_map][version] = "7.x-1.0"

projects[site_verify][version] = "7.x-1.0"

projects[smtp][version] = "7.x-1.0"

projects[strongarm][version] = "7.x-2.0"

projects[styleguide][version] = "7.x-1.1"

projects[superfish][version] = "7.x-1.8"

projects[taxonomy_display][version] = "7.x-1.1"

projects[taxonomy_menu][version] = "7.x-1.4"

projects[temple_user_list][version] = "7.x-1.1"

projects[text_resize][version] = "7.x-1.7"

projects[token][version] = "7.x-1.4"

projects[twitter][version] = "7.x-5.7"

projects[video][version] = "7.x-2.10"

projects[views][version] = "7.x-3.8"

projects[views_bulk_operations][version] = "7.x-3.1"

projects[views_litepager][version] = "7.x-3.0"

projects[views_slideshow][version] = "7.x-3.0"

projects[webform][version] = "7.x-3.20"

projects[webform_conditional][version] = "7.x-1.0-beta1"

projects[webform_conditional_confirmation][version] = "7.x-1.0"

projects[webform_rules][version] = "7.x-1.3"

projects[webform_validation][version] = "7.x-1.4"

projects[weight][version] = "7.x-2.1"

projects[wysiwyg][version] = "7.x-2.1"

projects[wysiwyg_filter][version] = "7.x-1.6-rc2"

projects[xautoload][version] = "7.x-2.7"

libraries[respondjs][download][type] = get
libraries[respondjs][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/respondjs.tgz"
libraries[respondjs][destination] = libraries

libraries[jquery.cycle][download][type] = get
libraries[jquery.cycle][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/jquery.cycle.tgz"
libraries[jquery.cycle][destination] = libraries

libraries[json2][download][type] = get
libraries[json2][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/json2.tgz"
libraries[json2][destination] = libraries

libraries[flexslider][download][type] = get
libraries[flexslider][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/flexslider.tgz"
libraries[flexslider][destination] = libraries

libraries[superfish][download][type] = get
libraries[superfish][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/superfish.tgz"
libraries[superfish][destination] = libraries

libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/ckeditor.tgz"
libraries[ckeditor][destination] = libraries

