; This file was auto-generated by Eastern Standard

api = 2
core = 7.x

; Acuiqa Drupal

projects[drupal][type] = "core"
projects[drupal][download][type] = "get"
;ver. 7.28
;projects[acquia][download][url] = "https://www.acquia.com/downloads/3175681/full/tar.gz"
;ver. 7.31
projects[drupal][download][url] = "http://www.acquia.com/downloads/3191106/full/zip"


; Modules

;projects[acquia_connector][version] = "7.x-2.14"

;projects[acquia_purge][version] = "7.x-1.0-beta2"

projects[] = adaptive_image

projects[] = admin_menu

;projects[] = admin_view ;Does not exist

projects[] = advanced_help

projects[] = auto_nodetitle

;projects[backup_migrate][version] = "7.x-2.4"

projects[] = bean

projects[block_class][version] = 1.1

projects[] = blockify

projects[] = calendar

projects[] = captcha

;projects[ckeditor][version] = "7.x-1.9"

projects[] = ckeditor_link

projects[] = coffee

projects[] = colorbox

projects[] = conditional_styles

projects[] = context

projects[] = ctoools

projects[] = date

projects[] = ddblock

projects[] = delta

projects[] = diff

projects[] = draggableviews

projects[] = ds

projects[] = email

projects[] = empty_page

projects[] = entity

projects[] = entityreference

projects[] = eva

projects[] = expire

projects[] = extlink

projects[] = fast_404

projects[] = features

projects[] = feeds

projects[] = feeds_xpathparser

projects[] = fences

projects[] = field_collection

projects[] = field_group

projects[] = field_permissions

projects[] = filefield_sources

projects[] = fontyourface

projects[] = front

projects[] = globalredirect

projects[] = google_analytics

projects[] = honeypot

projects[] = imce

projects[] = imce_wysiwyg

projects[] = job_scheduler

projects[] = jquery_plugin

projects[] = jquery_update

projects[] = ldap

projects[] = less

projects[] = libraries

projects[] = link

projects[] = linkchecker

projects[] = manual-crop

projects[] = media

projects[] = memcache

projects[] = menu_attributes

projects[] = menu_block

projects[] = menu_breadcrumb

projects[] = menu_position

projects[] = menu_views

projects[] = metatags_quick

projects[] = module_filter

;projects[mollom][version] = "7.x-2.6"

projects[] = node_clone

projects[] = node_export

projects[] = oauth

projects[] = omega_tools

projects[] = override_node_options

projects[] = page_title

projects[] = panels

projects[] = pathauto

projects[] = profile2

projects[] = profile2_regpath

projects[] = quickbar

projects[] = quicktabs

projects[] = readonlymode

;projects[] = recaptcha

projects[] = redirect

projects[] = references

projects[] = resp_img

projects[] = respondjs

projects[] = restrict_ip

projects[] = revisioning

projects[] = riddler

projects[] = rules

projects[] = save_draft

projects[] = scheduler

projects[] = securepages

projects[] = site_map

projects[] = site_verify

projects[] = smtp

projects[] = strongarm

projects[] = styleguide

projects[] = superfish

projects[] = taxonomy_display

projects[] = taxonomy_menu

;projects[temple_user_list][version] = "7.x-1.1" ;Does not exist

projects[] = text_resize

projects[] = token

;projects[twitter][version] = "7.x-5.7"

projects[] = video

projects[] = views

projects[] = views_bulk_operations

projects[] = views_litepager

projects[] = views_slideshow

projects[] = webform

projects[] = webform_conditional

projects[] = webform_conditional_confirmation

projects[webform_rules][version] = 1.3

projects[webform_validation][version] = 1.4

projects[] = weight

projects[] = wysiwyg

projects[wysiwyg_filter][download][type] = get
projects[wysiwyg_filter][download][url] = http://ftp.drupal.org/files/projects/wysiwyg_filter-7.x-1.6-rc2.tar.gz
projects[wysiwyg_filter][destination] = modules

;projects[] = xautoload

libraries[respondjs][download][type] = get
libraries[respondjs][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/respondjs.tgz"
libraries[respondjs][destination] = libraries

libraries[jquery.cycle][download][type] = get
libraries[jquery.cycle][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/jquery.cycle.tgz"
libraries[jquery.cycle][destination] = libraries

libraries[json2][download][type] = get
libraries[json2][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/json2.tgz"
libraries[json2][destination] = libraries

libraries[flexslider][download][type] = get
libraries[flexslider][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/flexslider.tgz"
libraries[flexslider][destination] = libraries

libraries[superfish][download][type] = get
libraries[superfish][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/superfish.tgz"
libraries[superfish][destination] = libraries

libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url] = "http://assets.temple.edu/sites/assets/files/libraries/tier2/ckeditor.tgz"
libraries[ckeditor][destination] = libraries

