; This file was auto-generated by Eastern Standard

api = 2
core = 7.x

; Acuiqa Drupal
;projects[acquia][type] = "core"
;projects[acquia][download][type] = "get"
;projects[acquia][download][url] = "https://www.acquia.com/downloads/3191106/full/tar.gz"

;via Drupal.org
projects[drupal][type] = "core"
projects[drupal][download][type] = "get"
projects[drupal][download][url] = "http://ftp.drupal.org/files/projects/drupal-7.34.tar.gz"

; Modules

;projects[acquia_connector][version] = "2.14"

;projects[acquia_purge][version] = "1.0-beta2"

projects[adaptive_image][version] = "1.4"

projects[admin_menu][version] = "3.0-rc3"

projects[admin_views][version] = "1.2"

projects[advanced_help][version] = "1.0"

projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][version] = "2.4"

projects[bean][version] = "1.7"

projects[block_class][version] = "1.1"

projects[blockify][version] = "1.2"

projects[calendar][version] = "3.4"

projects[captcha][version] = "1.0-beta2"

projects[ckeditor][version] = "1.16"

projects[ckeditor_link][version] = "2.2"

projects[coffee][version] = "1.0"

projects[colorbox][version] = "2.3"

projects[conditional_styles][version] = "2.1"

projects[context][version] = "3.2"

projects[ctools][version] = "1.4"

projects[date][version] = "2.8"

projects[ddblock][version] = "1.0"

projects[delta][version] = "3.0-beta11"

projects[diff][version] = "3.2"

projects[draggableviews][version] = "2.0"

projects[ds][version] = "2.4"

projects[email][version] = "1.2"

projects[empty_page][version] = "1.0"

projects[entity][version] = "1.4"

projects[entityreference][version] = "1.1"

projects[eva][version] = "1.2"

projects[expire][version] = "2.0-rc3"

projects[extlink][version] = "1.12"

projects[fast_404][version] = "1.3"

projects[features][version] = "2.0"

projects[feeds][version] = "2.0-alpha8"

projects[feeds_xpathparser][version] = "1.0-beta4"

projects[fences][version] = "1.0"

projects[field_collection][version] = "1.0-beta5"

projects[field_group][version] = "1.1"

projects[field_permissions][version] = "1.0-beta2"

projects[filefield_sources][version] = "1.9"

projects[fontyourface][version] = "2.5"

projects[front][version] = "2.1"

projects[globalredirect][version] = "1.5"

projects[google_analytics][version] = "1.3"

projects[honeypot][version] = "1.16"

projects[htmlpurifier][version] = "1.0"

projects[imce][version] = "1.6"

projects[imce_wysiwyg][version] = "1.0"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_plugin][version] = "1.0"

projects[jquery_update][version] = "2.2"

projects[ldap][version] = "2.0-beta8"

projects[less][version] = "2.6"

projects[libraries][version] = "2.0"

projects[link][version] = "1.0"

projects[linkchecker][version] = "1.1"

projects[main_menu_control][type] = module
projects[main_menu_control][download][type] = get
projects[main_menu_control][download][url] = "http://assets.temple.edu/sites/assets/files/modules/main_menu_control.tgz"

projects[manual-crop][version] = "1.4"

projects[media][version] = "1.4"

projects[memcache][version] = "1.0"

projects[menu_attributes][version] = "1.0-rc2"

projects[menu_block][version] = "2.3"

projects[menu_breadcrumb][version] = "1.3"

projects[menu_position][version] = "1.1"

projects[menu_views][version] = "2.0"

projects[metatags_quick][version] = "2.5"

projects[module_filter][version] = "1.7"

projects[mollom][version] = "2.12"

projects[node_clone][version] = "1.0-rc1"

projects[node_export][version] = "3.0"

projects[oauth][version] = "3.1"

projects[omega_tools][version] = "3.0-rc4"

projects[override_node_options][version] = "1.12"

projects[page_title][version] = "2.7"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[profile2][version] = "1.2"

projects[profile2_regpath][version] = "1.10"

projects[quickbar][version] = "2.0-beta1"

projects[quicktabs][version] = "3.6"

projects[readonlymode][version] = "1.1"

projects[recaptcha][version] = "1.8"

projects[redirect][version] = "1.0-rc1"

projects[references][version] = "2.0"

projects[resp_img][version] = "1.3"

projects[respondjs][version] = "1.1"

projects[restrict_ip][version] = "1.0-rc2"

projects[revisioning][version] = "1.8"

projects[riddler][version] = "1.2"

projects[rules][version] = "2.5"

projects[save_draft][version] = "1.4"

projects[scheduler][version] = "1.3"

projects[securepages][version] = "1.0-beta2"

projects[site_map][version] = "1.0"

projects[site_verify][version] = "1.0"

projects[smtp][version] = "1.0"

projects[strongarm][version] = "2.0"

projects[styleguide][version] = "1.1"

projects[superfish][version] = "1.8"

projects[taxonomy_display][version] = "1.1"

projects[taxonomy_menu][version] = "1.4"

projects[text_resize][version] = "1.7"

projects[token][version] = "1.4"

projects[tu_global][version] = "1.0-dev"

projects[twitter][version] = "5.7"

projects[video][version] = "2.10"

projects[views][version] = "3.8"

projects[views_bulk_operations][version] = "3.1"

projects[views_litepager][version] = "3.0"

projects[views_slideshow][version] = "3.0"

projects[webform][version] = "3.20"

projects[webform_conditional][version] = "1.0-beta1"

projects[webform_conditional_confirmation][version] = "1.0"

projects[webform_rules][version] = "1.3"

projects[webform_validation][version] = "1.4"

projects[weight][version] = "2.1"

projects[wysiwyg][version] = "2.1"

projects[wysiwyg_filter][version] = "1.6-rc2"

projects[xautoload][version] = "2.7"

libraries[respondjs][download][type] = get
libraries[respondjs][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier2/respondjs.tgz"
libraries[respondjs][destination]    = libraries

libraries[jquery.cycle][download][type] = get
libraries[jquery.cycle][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier2/jquery.cycle.tgz"
libraries[jquery.cycle][destination]    = libraries

libraries[json2][download][type] = get
libraries[json2][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier2/json2.tgz"
libraries[json2][destination]    = libraries

libraries[flexslider][download][type] = get
libraries[flexslider][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier2/flexslider.tgz"
libraries[flexslider][destination]    = libraries

libraries[superfish][download][type] = get
libraries[superfish][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier2/superfish.tgz"
libraries[superfish][destination]    = libraries

libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier2/ckeditor.tgz"
libraries[ckeditor][destination]    = libraries

