; This file was auto-generated by Eastern Standard

api = 2
core = 7.x

; Acuiqa Drupal

projects[acquia][type] = "core"
projects[acquia][download][type] = "get"
projects[acquia][download][url] = "https://www.acquia.com/downloads/3175681/full/tar.gz"

; Modules

projects[acquia_connector][version] = "2.14"

projects[acquia_purge][version] = "1.0-beta2"

projects[admin_views][version] = "1.2"

projects[backup_migrate][version] = "2.4"

projects[bean][version] = "1.7"

projects[block_visibility][version] = "1.0-beta2"

projects[blockify][version] = "1.2"

projects[ckeditor_link][version] = "2.2"

projects[conditional_styles][version] = "2.1"

projects[ctools][version] = "1.4"

projects[date][version] = "2.6"

projects[diff][version] = "3.2"

projects[draggableviews][version] = "2.0"

projects[ds][version] = "2.4"

projects[entity][version] = "1.3"

projects[entityreference][version] = "1.1"

projects[expire][version] = "2.0-rc3"

projects[fast_404][version] = "1.3"

projects[features][version] = "2.0"

projects[feeds][version] = "2.0-alpha8"

projects[feeds_xpathparser][version] = "1.0-beta4"

projects[fences][version] = "1.0"

projects[field_group][version] = "1.1"

projects[fontyourface][version] = "2.6"

projects[google_analytics][version] = "1.3"

projects[honeypot][version] = "1.16"

projects[imce][version] = "1.6"

projects[imce_wysiwyg][version] = "1.0"

projects[job_scheduler][version] = "2.0-alpha3"

projects[ldap][version] = "1.0-beta12"

projects[libraries][version] = "2.0"

projects[link][version] = "1.0"

projects[linkchecker][version] = "1.1"

projects[manual-crop][version] = "1.4"

projects[media][version] = "1.4"

projects[memcache][version] = "1.0"

projects[menu_attributes][version] = "1.0-rc2"

projects[menu_block][version] = "2.3"

projects[menu_breadcrumb][version] = "1.3"

projects[menu_editor][version] = "1.0-unstable3"

projects[metatags_quick][version] = "2.5"

projects[node_clone][version] = "1.0-rc1"

projects[page_title][version] = "2.7"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[quicktabs][version] = "3.6"

projects[readonlymode][version] = "1.1"

projects[redirect][version] = "1.0-rc1"

projects[revisioning][version] = "1.8"

projects[riddler][version] = "1.2"

projects[rules][version] = "2.4"

projects[save_draft][version] = "1.4"

projects[scheduler][version] = "1.0"

projects[securepages][version] = "1.0-beta2"

projects[site_map][version] = "1.0"

projects[smtp][version] = "1.0"

projects[styleguide][version] = "1.1"

projects[superfish][version] = "1.8"

projects[token][version] = "1.4"

projects[twitter][version] = "3.3"

projects[views][version] = "3.8"

projects[views_bulk_operations][version] = "3.1"

projects[views_litepager][version] = "3.0"

projects[webform][version] = "3.20"

projects[weight][version] = "2.1"

projects[wysiwyg][version] = "2.2"

libraries[tinymce][download][type] = get
libraries[tinymce][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier1/tinymce.tgz"
libraries[tinymce][destination]    = libraries

libraries[superfish][download][type] = get
libraries[superfish][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier1/superfish.tgz"
libraries[superfish][destination]    = libraries

libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url]  = "http://assets.temple.edu/sites/assets/files/libraries/tier1/ckeditor.tgz"
libraries[ckeditor][destination]    = libraries

